- name: manage timezone America/Chicago
  timezone:
    name: America/Chicago

- name: ensure docker.io is installed
  apt:
    name: docker.io
    state: latest
    update_cache: yes

- name: ensure docker pip package is installed
  pip:
    name: docker
    state: latest
