- name: "{{ nginx_container_name }} config directory"
  file:
    path: "{{ owncloud_volume_dir }}/{{ nginx_container_name }}"
    state: directory
    recurse: true

- name: "{{ nginx_container_name }} config"
  template:
    src: nginx.conf.j2
    dest: "{{ owncloud_volume_dir }}/{{ nginx_container_name }}/nginx.conf"
  notify:
    - restart nginx

- name: "{{ nginx_container_name }} container"
  docker_container:
    name: "{{ nginx_container_name }}"
    image: nginx:latest
    restart_policy: always
    links:
      - "{{ owncloud_container_name }}"
    ports:
      - "{{ ip_address }}:443:443"
      - "{{ ip_address }}:80:80"
    healthcheck:
      test: ["CMD", "service", "nginx", "status"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - "{{ owncloud_volume_dir }}/{{ nginx_container_name }}/nginx.conf:/etc/nginx/conf.d/default.conf"
      - /etc/letsencrypt:/etc/letsencrypt
