- name: "{{ owncloud_container_name }} container"
  docker_container:
    name: "{{ owncloud_container_name }}"
    image: "owncloud/server:{{ owncloud_version }}"
    restart_policy: always
    links:
      - "{{ db_container_name }}"
      - "{{ redis_container_name }}"
    env:
      OWNCLOUD_DOMAIN: "{{ fqdn }}"
      OWNCLOUD_DB_TYPE: mysql
      OWNCLOUD_DB_NAME: "{{ db_name }}"
      OWNCLOUD_DB_USERNAME: "{{ db_username }}"
      OWNCLOUD_DB_PASSWORD: "{{ db_password }}"
      OWNCLOUD_DB_HOST: "{{ db_container_name }}"
      OWNCLOUD_ADMIN_USERNAME: "{{ owncloud_admin_username }}"
      OWNCLOUD_ADMIN_PASSWORD: "{{ owncloud_admin_password }}"
      OWNCLOUD_MYSQL_UTF8MB4: "true"
      OWNCLOUD_REDIS_ENABLED: "true"
      OWNCLOUD_REDIS_HOST: "{{ redis_container_name }}"
    healthcheck:
      test: ["CMD", "/usr/bin/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - "{{ owncloud_volume_dir }}/{{ owncloud_container_name }}/data:/mnt/data"